### ISSUE TITLE
How know what component is presented?

### ISSUE THREAD

**Issue by luisfuertes** [efkan/rndrawer-implemented-rnrouter#15]
Im trying to add style bold the Drawer selected option.

But i dont know how can acces in "SideDrawerContent" to Navigator or how can obtain what component is presented in that moment

Can you help me?

**Comment by efkan** [comment]
I use Redux to update UI.

I guess to solve this issue have to dig the RNRF props. 

If you find out a relevant RNRF prop (assume there is a currentRoute prop which contains the current route's name) and give as a prop to the drawer [here](https://github.com/efkan/rndrawer-implemented-rnrouter/blob/master/src/Example.js#L104) then you can pass that prop [here](https://github.com/efkan/rndrawer-implemented-rnrouter/blob/master/src/SideDrawer.js#L11) to the `SideDrawerContent.js`. 

And finally you can check the prop and give a new style according to the prop value.

But, if I remember correct, this solution can not handle `Actions.pop()` action. This is because why I started to use Redux.

If you want to prepare a production by using React-Native I recommend using of Flux or one of its derivatives. It would be beneficial.

**Flux sites**: [Github](https://github.com/facebook/flux) - [Homepage](http://facebook.github.io/flux/)

Some popular **Flux derivatives/suchlike** frameworks;

**Redux.....:** [Github](https://github.com/rackt/redux/) - [Homepage](http://redux.js.org/) - [A Free Course by Its Creator](https://egghead.io/series/getting-started-with-redux)

**Reflux.....:** [Github](https://github.com/reflux/refluxjs)

**Alt...........:** [Github](https://github.com/goatslacker/alt) - [Homepage](http://alt.js.org/) 

**Flummox:** [Github](https://github.com/acdlite/flummox) - [Homepage](http://acdlite.github.io/flummox)

**Yahoo / Fluxible:** [Github](https://github.com/yahoo/fluxible) - [Homepage](http://fluxible.io/)

**Nuclear-js..........:** [Github](https://github.com/optimizely/nuclear-js) - [Homepage](https://optimizely.github.io/nuclear-js/)

**Comment by efkan** [comment]
Flux (Redux or whatever) allow you to use a global state like the component state in react-native.

**Comment by luisfuertes** [comment]
Thanks for answer.

Im using Redux. I understand your answer but dont know in what prop can i find the current route. 

"SideDrawer" render only call 1 time in all app.

Where can i find the current route name?

**Comment by efkan** [comment]
Your Redux usage is a good news :smiley: 

If I remember correct I set a `currentRoute` in my Route reducer I wrote the below;
_(When calling `Action.pop()` or `Action.Login` RNRF dispatch an action automatically)_

```
import { Actions, } from 'react-native-router-flux'

function currentRoute(state = '', action) {
    switch (action.type) {
    case Actions.AFTER_ROUTE:
    case Actions.AFTER_POP:
        return action.name
    /* If the lines below are used in this reducer (currentRoute) it causes a sync problem  */
    // case Actions.BEFORE_ROUTE:
    // case Actions.BEFORE_POP:
    // case Actions.AFTER_FOCUS:
    // case Actions.BEFORE_FOCUS:
    // case Actions.AFTER_DISMISS:
    // case Actions.BEFORE_DISMISS:
    default:
        return state
    }
}


function beforeRoute(state = '', action) {
    switch (action.type) {
    /* If the lines below are used in this reducer (currentRoute) it causes a sync problem  */
    case Actions.BEFORE_ROUTE:
    case Actions.BEFORE_POP:
    // case Actions.AFTER_FOCUS:
    // case Actions.BEFORE_FOCUS:
    // case Actions.AFTER_DISMISS:
    // case Actions.BEFORE_DISMISS:
        return action.name
    default:
        return state
    }
}

function afterFocusRoute(state = '', action) {
    switch (action.type) {
    case Actions.AFTER_FOCUS:
        return action.name
    default:
        return state
    }
}

export {
    beforeRoute,
    currentRoute,
    afterFocusRoute,
}


```

Hope it works for you..

**Comment by luisfuertes** [comment]
It works! Thanks!
