### ISSUE TITLE
Only one default export allowed per module

### ISSUE THREAD

**Issue by ghost** [efkan/rndrawer-implemented-rnrouter#20]
i run react-native run-android command then i got this error 

/node_modules.@exponent/react-native-navigator/ExRouteRenderer.js: Only one default export allowed per module

**Comment by efkan** [comment]
Hi,

I've checked `ExRouteRenderer.js`. Only one `export` line I could found. I have to ask some questions:

- Did you take steps according to the [installation documentation](https://github.com/efkan/rndrawer-implemented-rnrouter#installation)?
- Did you make a change in file? 

Last year it was working.

Note: IMHO if you look for either a simple sample or a scaffold you should use [react-navigation](https://reactnavigation.org/). Because `react-native-drawer` is not appropriate to use in product.

**Comment by efkan** [comment]
I'm closing the issue because it seems inactive.

If you have another issue, don't hesitate to ask..
