### ISSUE TITLE
Undefined is not an object evaluating _this2.drawer.open

### ISSUE THREAD

**Issue by jayesbe** [efkan/rndrawer-implemented-rnrouter#5]
I tried to implement the drawer according to the example.  In fact I copied the main bits exactly SideDrawer and SideDrawerContent.

The Router is also nearly the same as the example

```
            <SideDrawer 
              ref={c => { c ? this.drawer = c.drawer : this.drawer }}
            >
              <Router name="drawerRoot" hideNavBar={true} footer={TabBar} tabBarStyle={style.tabBar} navigationBarStyle={style.navigationBar}>
(some routes here)
              </Router>
            </SideDrawer>
```

but I keep getting an error of Undefined is not an object.

**Comment by jayesbe** [comment]
Only difference I see is the example is on RN 0.20 and I am on RN 0.21

**Comment by jayesbe** [comment]
I think I found the issue

```
renderLeftButton={this.renderMenuButton}
```

should be 

```
renderLeftButton={this.renderMenuButton.bind(this)}
```

that fixed it for me. should I make a PR ?

**Comment by efkan** [comment]
Hi,
To test your issue I've initialized a new project by using `react-native init RNDrawerImplementedRNRouter` command. 
Then I copied the **_src**_ folder, **_index.android.js**_ and **_package.json**_ files.
Then I changed react-native version to "^0.21.0" in json file.
Then run the command of `npm install` in the project folder.
Then I changed the first parameter of  `AppRegistry.registerComponent()` function in index.android.js file.
Then I run `react-native start`. Now I can use the example app in the emulator. So it works.

I'm wondering that did you try on IOS or Android?
Unfortunately I have never tried on an IOS because of I haven't any Apple product.

**Comment by jayesbe** [comment]
You are right!

Sorry. There is one other difference. my Schema is actually outside the Router. In the example.. you have the Schema on the same level as the associated Routes. I have it higher up. I didn't realize the difference in context.

**Comment by efkan** [comment]
Thank you for the PR suggestion. Actually it shouldn't be with `.bind` function because it's not necessary if the function is written by `renderMenuButton = () => {  ... }` notation.

**Comment by jayesbe** [comment]
thanks. Will close this off.
