### ISSUE TITLE
'props should be defined for stack'

### ISSUE THREAD

**Issue by shivangbtech** [efkan/rndrawer-implemented-rnrouter#6]
getting error :
'props should be defined for stack',
How to resolve it.

**Comment by efkan** [comment]
Probably you try the last version of `react-native-router-flux`.
This example use version 2.X.

You could use the command of `npm install react-native-router-flux@2.3.9` to benefit from the example.

Feel free to ask about somethings if your issue continues although this issue is closed.

https://github.com/aksonov/react-native-router-flux/issues/524#issuecomment-212391225

**Comment by shivangbtech** [comment]
Yes, Its working. Thanks.
