### ISSUE TITLE
Update react-native-router-flux v3.x, react-native-drawer v2.x

### ISSUE THREAD

**Issue by cemolcay** [efkan/rndrawer-implemented-rnrouter#8]
HI, thanks for the great example! But unfortunately its kind of old now.
Can you update the project with the latest versions of packages? 
Both router and drawer packages has breaking changes since this version.

Thank you.

**Comment by efkan** [comment]
Hi,
this is not possible for now. Becuase both of RNRF and Drawer components are not stable yet. I'd tried out them recently. The updating these tools needs some time.

**Comment by luisfuertes** [comment]
Im trying it now. It remains not stable?

**Comment by efkan** [comment]
Actually yes. The newest `react-native-router-flux` library uses `react-native-experimental-navigation`. Check [this](https://github.com/aksonov/react-native-router-flux/blob/master/package.json#L40) out. 
For a couple months, I didn't try the newest version of `react-native-drawer`.

**Comment by efkan** [comment]
Nevertheless if you want to use their new versions in your production, asking to creators would be good. 
On the other hand both of them have a lot of users as far as I know

**Comment by octohedron** [comment]
Hello @efkan, Is it possible to run the example with newer versions of react native? I'm trying it with react-native 0.29.1 and it's throwing a bunch of errors about the syntax, after downgrading react-native-router-flux from 3.x to 2.2.7

**Comment by efkan** [comment]
Hello @octohedron , I use in React-Native v0.27. 
If I remember correctly I'd encountered with the same syntax errors.
I corrected the errors manually. 
The errors were about separating of `react` library and its some methods from `react-native`. Because of this reason, installing this repo together with old versions of `react-native-router-flux` and `react-native-drawer` on a new version `react-native` cause the errors.

I recommend trying the latest versions both of `react-native-router-flux` and `react-native-drawer`.

If I don't have an opportunity these days to try the latest version and update this repo.

**Comment by octohedron** [comment]
Hi @efkan, thank you for your answer.

I tried the latest version of `react-native-router-flux` but I couldn't run your example, so I downgraded it and got the errors from `react-native`, I really don't want to downgrade my whole application platform just to fix this, I will try to refactor the code myself

**Comment by efkan** [comment]
Ooops.. 
Sorry, I meant you might try the latest versions in your own solution. Without this repo.

It's not so hard. Just take a little time. React-native-router-flux has good examples includes an example with React-native-drawer. 

Also if you use this example then most likely you want to upgrade some day.

New React-native-router-flux has a lot changes. I recommend learning it instead of this obsolete version.
